Support Gnome 41
ifl0w/RandomWallpaperGnome3 pull request #114
Opened 2021-10-05 15:54 UTC by candrews

Confirmed working on Gnome 41 by disabling extension version checks using `gsettings set org.gnome.shell disable-extension-version-validation "true"` and running the current, latest version of this extension provided at https://extensions.gnome.org/extension/1040/random-wallpaper/

2021-11-11 07:58 UTC, AlexWayfer approved these changes

2021-11-11 07:59 UTC, AlexWayfer commented
@ifl0w GNOME 41 has been released.

2021-11-16 03:22 UTC, ifl0w requested changes
Thanks for the PR and testing the extension on the new shell version! 

Bumping the release versions should not be done in this PR IMO.
I'll increase the version numbers when I have merged other PRs and right before I release it

2021-11-16 03:22 UTC, ifl0w commented on randomwallpaper@iflow.space/metadata.json
> +  "version": 27,
```suggestion
  "version": 26,
```

2021-11-16 03:22 UTC, ifl0w commented on randomwallpaper@iflow.space/metadata.json
> +  "semantic-version": "2.7.0",
```suggestion  
  "semantic-version": "2.6.0",
```

2021-11-16 03:23 UTC, ifl0w commented
Also sorry for being so unresponsive lately! I'll release the next version as soon as possible.

2021-11-16 03:30 UTC, ifl0w approved these changes
Never mind, I'll simply merge this PR as the last one. So there is nothing to complain about :P 

Thanks for the PR!

2021-12-15 13:43 UTC, merged