Decouple preference window from wallpaperController (Requires #141)
ifl0w/RandomWallpaperGnome3 pull request #144
Opened 2022-12-12 01:21 UTC by Lucki

I've decoupled the preferences window from all background activity. The background controller now tracks some gsetting changes to communicate with the preferences window. I'm confident this fixes #135 since there's now only one single `wallpaperController` running.

This also fixes #126 - just use your favorite keyboard shortcut manager (like gnomes in settings -> keyboard -> shortcuts -> own shortcuts) to set the variable `request-new-wallpaper` to `true`:
~~~
gsettings --schemadir "${XDG_DATA_HOME:-$HOME/.local/share}/gnome-shell/extensions/randomwallpaper@iflow.space/schemas" set org.gnome.shell.extensions.space.iflow.randomwallpaper.backend-connection request-new-wallpaper true
~~~

2022-12-14 21:58 UTC, ifl0w commented
@Lucki would you be so kind to `git rebase` this PR on the `WIP_3.0.0` branch. Not sure if this is handled automatically by git since the commit hashes are different. You might have to drop the first three commits manually to remove the duplicate/conflicting commits from the PR.

Sorry for the extra effort!

2022-12-14 23:29 UTC, Lucki commented
All done! GitHub got this correctly and no commit dropping was required.

2023-02-17 00:00 UTC, ifl0w requested changes
Thanks agian! This is a very interesting and exciting change! Is it good practice to use gschemas as IPC mechanism, though?

Generally, I'm fine with it and interested in how that works out! Also, a cool side effect is that now the wallpaper change can be triggered from other applications/languages as well! 

I only added a small comment.

2023-02-17 01:39 UTC, Lucki commented on randomwallpaper@iflow.space/wallpaperController.js
> -			this._backendConnection.set('request-new-wallpaper', 'boolean', false);
I also must have noticed this. It'll land in a `finally{}` eventually :+1: 

~~~ ts
try {
    await this.fetchNewWallpaper();
} finally {
    this.update();
    this._backendConnection.setBoolean('request-new-wallpaper', false);
}
~~~

2023-02-17 01:43 UTC, Lucki commented
> Is it good practice to use gschemas as IPC mechanism, though?

I honestly don't know but since you already had the observer mechanism in place it wasn't a far to this.

2023-02-19 17:56 UTC, ifl0w commented
> I honestly don't know but since you already had the observer mechanism in place it wasn't far to this.

Yeah, let's try and see how this works out! The only thing I want to avoid is accepting some (potentially unsafe) user input via this backend-connection.

2023-02-19 18:01 UTC, ifl0w commented
Again, I ask you to rebase the commit. Sorry for that! 
If this is too annoying to you, then I could pull in your changes directly without handling the PR in the GitHub UI, but I honestly don't know if I can make the GitHub interface pick up the manual changes correctly.

2023-02-19 21:27 UTC, Lucki commented
Hm, strange that this doesn't work automatic. It worked automatic locally and GitHub doesn't even register anything different in the force push…

Guess I have to rebase every PR when the previous one is merged then.

2023-02-20 23:19 UTC, ifl0w commented
Yeah, exactly; these boolean triggers won't be an issue at all. I just realized that I have to look at all the other schemas in general and see what exactly is stored there and how it is used because I never thought about it a lot.

Yeah, the hashes change once it is merged and it is a bit annoying that GH does not recognize this.

2023-02-20 23:26 UTC, ifl0w approved these changes

2023-02-20 23:26 UTC, merged