Final changes for upcoming release
ifl0w/RandomWallpaperGnome3 pull request #198
Opened 2024-03-26 00:51 UTC by ifl0w

2024-04-04 23:59 UTC, ifl0w commented
@Lucki can you double-check these commits here before I create the release? :)

2024-04-06 00:00 UTC, Lucki requested changes
I haven't tried it yet. I fear that after a new login the zoom mode will change - I report later on that.

Edit: Yes, as I suspected, it doesn't work.

---

Other than that, there's the now duplicated reset function. Do we need that extra safety, is the function provided by GJS not enough?

And other than that that: :+1:

2024-04-06 10:19 UTC, Lucki commented on src/prefs.ts
> +        });
With the above things in mind, this also has the same problem.
This forces the `spanned` mode for multi-monitor setups back into a single screen wallpaper.

2024-04-07 23:20 UTC, ifl0w commented
> Sorry, this doesn't work. This resets the background zoom option always back to zoom on logout/reboot/suspend. 

Hm, right. I didn't think about that. :man_facepalming: 

With these insights, I gravitate back to the idea of directly hooking into the system settings instead of having a copy in the extension settings. In the end, Gnome extensions aren't really external programs but rather mutations of the DE, so it is somewhat reasonable to alter the settings directly. We already do this anyway with the wallpaper path itself. 

Advantages: 
* No mapping between the two settings is required, thus less room for error.
* Easier to display and change the current state in the extension settings. 

Disadvantage:
* The spanned state will be displayed in the settings when it is activated by the manager (could be seen as an advantage in terms of transparency)

2024-04-07 23:22 UTC, ifl0w commented on src/manager/wallpaperManager.ts
> +    }
Oh, haha ... well should have RTFM ... :D
But I'll probably drop the commit anyway because of the other shortcomings you pointed out.

2024-04-07 23:23 UTC, ifl0w commented on src/schemas/org.gnome.shell.extensions.space.iflow.randomwallpaper.gschema.xml
> +            <default>2</default>
No problem! 

This kind of issue would also be mitigated by not duplicating the settings, I guess.

2024-04-09 15:08 UTC, Lucki commented
I also see this disadvantage:
* Turning off multi-monitor requires setting two steps: Turning the option itself off and also setting the zoom mode to something different from spanned. This could be done automatically, but then we're defining a default again, which might be insufficient. I don't know how often that happens though.

2024-04-17 23:51 UTC, ifl0w commented
>Turning off multi-monitor requires setting two steps: Turning the option itself off and also setting the zoom mode to something different from spanned. This could be done automatically, but then we're defining a default again, which might be insufficient. I don't know how often that happens though.

Hmm, you are right, but I think this is a reasonable trade-off. I'll give it a try and test if that works better. If not, I'll just revert my problematic changes.

2024-05-05 21:35 UTC, ifl0w commented
@Lucki I finally got around to giving this another quick try. If you still see some fundamental issues, then I'll just revert my stuff for creating a release, but I think this should be reasonable now. :sweat_smile: 
Can you give it a try with your multi-monitor setup? 

Also, I renamed the "Zoom Mode" to "Scaling Mode" as I think this is more fitting.

2024-05-06 13:23 UTC, Lucki commented
Gave it a quick test and it seems to work.

2024-05-09 11:53 UTC, merged